module.exports.userModel = require('./user.model')
module.exports.articleModel = require('./article.model')
module.exports.categoryModel = require('./category.model')
module.exports.commentModel = require('./comment.model')
module.exports.likeModel = require('./like.model')